import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

export interface VisitorSite {
  id: string;
  user_id: string;
  name: string;
  domain: string | null;
  site_key: string;
  allowed_origins: string[];
  is_active: boolean;
  created_at: string;
}

export interface VisitorCompany {
  user_id: string;
  site_id: string;
  /**
   * Identity of the visiting company: the reverse-IP domain when the provider
   * returned one, the normalised name otherwise. Only the paid ipapi.is tier
   * returns domains, so on the free tier this is a name for every row.
   */
  company_key: string;
  company_domain: string | null;
  company_name: string | null;
  country: string | null;
  city: string | null;
  last_path: string | null;
  last_referrer: string | null;
  matched_company_id: string | null;
  page_views: number;
  visit_count: number;
  unique_pages: number;
  first_seen: string;
  last_seen: string;
}

export interface WebsiteVisit {
  id: string;
  site_id: string;
  session_id: string | null;
  visited_at: string;
  path: string | null;
  page_title: string | null;
  referrer: string | null;
  utm_source: string | null;
  utm_medium: string | null;
  utm_campaign: string | null;
  country: string | null;
  region: string | null;
  city: string | null;
  company_name: string | null;
  company_domain: string | null;
  asn_name: string | null;
  classification: "company" | "isp" | "hosting" | "bot" | "unknown";
  matched_company_id: string | null;
  resolver: string | null;
}

/** Cut-off timestamp for a "last N days" filter. */
export function sinceDays(days: number): string {
  return new Date(Date.now() - days * 86_400_000).toISOString();
}

export function useVisitorSites() {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["visitor_sites", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("visitor_sites")
        .select("*")
        .order("created_at", { ascending: true });
      if (error) throw error;
      return data as unknown as VisitorSite[];
    },
    enabled: !!user,
  });
}

/**
 * Creates the first site for a user. The site_key is generated by the database
 * so it never has to travel through the client.
 */
export function useCreateVisitorSite() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (site: { name: string; domain?: string | null }) => {
      const { data: { user } } = await supabase.auth.getUser();
      const { data, error } = await supabase
        .from("visitor_sites")
        .insert({
          name: site.name,
          domain: site.domain ?? null,
          user_id: user!.id,
        } as never)
        .select()
        .single();
      if (error) throw error;
      return data as unknown as VisitorSite;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["visitor_sites"] }),
  });
}

export function useVisitorCompanies(days: number) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["website_visitor_companies", days, user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("website_visitor_companies")
        .select("*")
        .gte("last_seen", sinceDays(days))
        .order("last_seen", { ascending: false });
      if (error) throw error;
      return data as unknown as VisitorCompany[];
    },
    enabled: !!user,
  });
}

export function useWebsiteVisits(days: number, limit = 500) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["website_visits", days, limit, user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("website_visits")
        .select(
          "id, site_id, session_id, visited_at, path, page_title, referrer, " +
          "utm_source, utm_medium, utm_campaign, country, region, city, " +
          "company_name, company_domain, asn_name, classification, " +
          "matched_company_id, resolver",
        )
        .gte("visited_at", sinceDays(days))
        .order("visited_at", { ascending: false })
        .limit(limit);
      if (error) throw error;
      return data as unknown as WebsiteVisit[];
    },
    enabled: !!user,
  });
}

/**
 * The pages one identified company looked at, newest first.
 *
 * Matched on domain where there is one and on the exact name otherwise, which
 * mirrors how the view builds company_key — a name-keyed visitor has no domain
 * to filter on, and filtering on the null would return every unresolved row.
 */
export function useCompanyVisits(visitor: VisitorCompany | null, days: number) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["website_visits_by_company", visitor?.company_key, days, user?.id],
    queryFn: async () => {
      let query = supabase
        .from("website_visits")
        .select(
          "id, site_id, session_id, visited_at, path, page_title, referrer, " +
          "utm_source, utm_medium, utm_campaign, country, region, city, " +
          "company_name, company_domain, asn_name, classification, " +
          "matched_company_id, resolver",
        )
        .gte("visited_at", sinceDays(days))
        .order("visited_at", { ascending: false })
        .limit(200);

      query = visitor!.company_domain
        ? query.eq("company_domain", visitor!.company_domain)
        : query.eq("company_name", visitor!.company_name!);

      const { data, error } = await query;
      if (error) throw error;
      return data as unknown as WebsiteVisit[];
    },
    enabled: !!user && !!visitor,
  });
}

/**
 * Promotes an identified visitor to a CRM company and back-links every visit
 * from that domain, so the company page shows the browsing history.
 */
export function useAddVisitorToCrm() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (visitor: VisitorCompany) => {
      const { data: { user } } = await supabase.auth.getUser();

      const { data: company, error } = await supabase
        .from("companies")
        .insert({
          user_id: user!.id,
          company_name: visitor.company_name || visitor.company_key,
          // Only when reverse-IP actually returned a domain. Interpolating a
          // null produced the literal string "https://null" on the free tier.
          website: visitor.company_domain ? `https://${visitor.company_domain}` : null,
          domains: visitor.company_domain,
          country: visitor.country,
          labels: "Website visitor",
          last_interaction: visitor.last_seen,
        } as never)
        .select("id")
        .single();
      if (error) throw error;

      const companyId = (company as { id: string }).id;
      const backlink = supabase
        .from("website_visits")
        .update({ matched_company_id: companyId } as never);
      await (visitor.company_domain
        ? backlink.eq("company_domain", visitor.company_domain)
        : backlink.eq("company_name", visitor.company_name!));

      return companyId;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["website_visitor_companies"] });
      qc.invalidateQueries({ queryKey: ["website_visits"] });
      qc.invalidateQueries({ queryKey: ["companies"] });
    },
  });
}
