// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getqcxnjsohtlagscmfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldHFjeG5qc29odGxhZ3NjbWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NjMyNDksImV4cCI6MjA3NzMzOTI0OX0.pUQXYLcuZXvYpwUPZGmwAcPW_eMf3J7qEtuTQYh-xZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});